config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'
  #
  # get 'password_resets/edit'

  root 'welcome#index'
  get('/change_password', {to:'users#edit_password'})
  put('/change_password', {to:'users#update_password'})

  resources :posts do
    resources :comments, only: [:create, :destroy, :index]
    resources :likes, only: [:create]
  end



  resources :users, only:[:index, :new, :create, :update, :edit]
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
    #get rid of ":id" in the url
  end
  resources :password_resets, only: [:new, :create, :edit, :update]


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  # before_action :authenticate_user!, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]    # Case (1)

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      session[:user_id] = @user.id
      flash[:success] = "Password has been reset."
      redirect_to posts_path
    else
      render 'edit'                                     
    end
  end

  private
  def get_user
    @user = User.find_by(email: params[:email])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  def check_expiration
    if @user.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>

<% provide(:title, 'Reset password') %>
<h1>Reset password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%# render 'shared/error_messages' %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/edit_password.html.erb
<div class="row" id="changePassword">
    <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>Change Password</h3>
        </div>
        <div class="panel-body">
          <%= form_tag change_password_path, method: :put do %>
            <hr>
              <div class="form-group">
                <%= password_field_tag :current_password, nil, class:'form-control input-md', placeholder: "Current_password" %>
              </div>
              <div class="form-group">
                <%= password_field_tag :new_password, nil, class:'form-control input-md', placeholder: "New_password" %>
              </div>
              <div class="form-group">
                <%= password_field_tag :new_password_confirmation, nil, class:'form-control input-md', placeholder: "New_password_confirmation" %>
              </div>
            <hr>
            <div class="row">
              <div class="col-xs-12 col-md-6">
                <%= submit_tag "Update Password", class: "btn btn-primary btn-block btn-md input-md" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
  <style>
    footer{
            position:fixed;
            right:0px;
            left:0px;
            bottom: 5vh;
          }
  </style>

app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<% provide(:title, "Forgot password") %>

<div class="row" id="resetPassword">
  <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>Forgot Password</h3>
      </div>
      <div class="panel-body">

        <%= form_for(:password_reset, url: password_resets_path) do |f| %>

          <%= f.label :email %>

          <div class="form-group">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.submit "Submit", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>