config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'
  #
  # get 'password_resets/edit'

  root 'welcome#index'
  get('/change_password', {to:'users#edit_password'})
  put('/change_password', {to:'users#update_password'})

  resources :posts do
    resources :comments, only: [:create, :destroy, :index]
    resources :likes, only: [:create]
  end



  resources :users, only:[:index, :new, :create, :update, :edit]
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
    #get rid of ":id" in the url
  end
  resources :password_resets, only: [:new, :create, :edit, :update]


end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true

  def formatted_date
    created_at.strftime('%A, %B %d, %Y')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :get_post, only:[:show, :update, :edit, :destroy]
  before_action :post_params, only:[:update, :create]

  def index
    @posts = Post.where.not(id: Post.last).last(9)
    @last_post = Post.last
    @most_liked = Post.left_joins(:likes).group(:id).order("COUNT(post_id) DESC").limit(5)
    @number = 10
  end

  def new
    @post = Post.new
  end

  def create
    # post_params = params.require(:post).permit([:title, :body, :category_id])
    @post = Post.new (post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path({id: @post.id })
    else
      render :new
    end
  end

  def show
    @number = 2
    # @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    # try to limit number of the displaying comments
    if !(@post.likes.find_by_user_id(current_user))
      @liked_by_currentuser = false
    else
      @liked_by_currentuser = true

    end
    @like = Like.new

  end

  def destroy
    # @post = Post.find params[:id]
    if !can? :destroy, @post
      redirect_to root_path, alert:'Access denied!'
    else
      @post.destroy
      redirect_to posts_path, notice:'Post Deleted!'
    end
  end

  def edit
    # @post = Post.find(params[:id])
    redirect_to root_path, alert:'Access denied!' unless can? :edit, @post

  end

  def update

    # @post = Post.find(params[:id])
    # post_params = params.require(:post).permit([:title, :body, :category_id])
    if !can? :edit, @post
      redirect_to root_path, alert:'Access denied!'
    elsif @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  private
  def get_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit([:title, :body, :category_id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<%= @post.errors.full_messages.join(', ') %>
<div class="container" id="editPost">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1>Edit post</h1>
			<%= form_for @post do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, rows:"8", class:"form-control"%>
			</div>
			<div class="form-group">
				<%= f.label :category_id %>
				<%= f.collection_select :category_id, Category.order(:name), :id, :name %>
			</div>
			<div class="form-group">
				<%= f.submit "Update", class:"btn btn-primary"%>
			</div>
			<% end %>
		</div>
	</div>
</div>

<style>
  footer {
    position:fixed;
    right:0px;
    left:0px;
    bottom: 5vh;
  }
</style>

app/views/posts/index.html.erb
<br>
<div class="container">
  <div class="row" id="most_liked">
    <div class="col-lg-8" id="most_liked_image">
      <div class="row">
        <%= image_tag 'post1.jpg', style: 'width: 100%', class:"img-responsive" %>
      </div>
      <br>
      <div class="row">
        <span class="glyphicon glyphicon glyphicon-heart-empty"></span>
        <span><%= @last_post.likes.count %></span>
        <span class="glyphicon glyphicon glyphicon-bookmark pull-right"></span>
      </div>
      <div class="row">
        <h3><%= link_to @last_post.title, post_path(@last_post.id) %></h3>
        <p><%= @last_post.body %></p>
        <a href="#">
          <p><%= User.find(@last_post.user.id).first_name %>
            <%= User.find(@last_post.user.id).last_name %></p>
        </a>
        <span><%= @last_post.formatted_date %></span>
      </div>
    </div>
    <div class="col-lg-4" id="most_liked_text">
      <div class="row">
        <h3>Most Liked</h3>
      </div>
      <% @most_liked.each do |post| %>
      <div class="row">
        <h5><%= link_to post.title, post_path(post.id) %></h5>
      </div>
      <% end %>
    </div>
  </div>
  <br>
  <br>

  <%# @posts.each_slice(3) do |group|%>
  <% @posts.in_groups(3) do |group|%>
  <div class="row" id="posts">
    <% group.each do |post| %>
    <div class="col-lg-4">
      <div class="row">
        <%= image_tag "post#{@number}.jpg", style: 'width: 100%', class:"img-responsive" %>
      </div>
      <br>
      <div class="row">
        <span class="glyphicon glyphicon glyphicon-heart-empty"></span>
        <span><%= post.likes.count%></span>
        <span class="glyphicon glyphicon glyphicon-bookmark pull-right"></span>
      </div>
      <div class="row">
        <h3><%= link_to post.title, post_path(post.id) %></h3>
        <p><%= post.body %></p>
        <a href="#">
          <p><%= User.find(post.user.id).first_name %>
            <%= User.find(post.user.id).last_name %></p>
        </a>
        <span><%= post.formatted_date %></span>
      </div>
    </div>
    <% @number -= 1 %>
    <% end %>
  </div>

  <br>
  <br>
  <% end %>
  <div class="row" id="more_Article">
    <a href="#" class="btn btn-info btn-lg" role="button">More Article</a>
  </div>
  <br>
  <hr>

app/views/posts/new.html.erb
<%# @post.errors.full_messages.join(', ') %>
<div class="container" id="createPost">
	<div class="row">
		<div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
			<h1>Create post</h1>
			<%= form_for @post do |f| %>
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class:"form-control" %>
			</div>
			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, rows:"8", class:"form-control"%>
			</div>
			<div class="form-group">
				<%= f.label :category_id %>
				<%= f.collection_select :category_id, Category.order(:name), :id, :name %>
			</div>
			<div class="form-group">
				<%= f.submit "Create", class:"btn btn-primary"%>
			</div>
			<% end %>
		</div>
	</div>
</div>

<style>
  footer {
    position:fixed;
    right:0px;
    left:0px;
    bottom: 5vh;
  }
</style>
<!-- <%# form_for @post do |f| %>
  <div>
    <%# f.label :category_id %>
    <%# f.text_field :category_id %>
  </div>
  <div>
    <%# f.label :title %>
    <%# f.text_field :title %>
  </div>
  <div>
    <%# f.label :body %>
    <%# f.text_area :body %>
  </div>
  <%# f.submit %>
<%# end %> -->

app/views/posts/show.html.erb
<div class="container-fluid">

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        <h2><%= @post.title %></h2>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
          <h2>
          <span class="glyphicon glyphicon glyphicon-heart-empty"></span>
          <span><%= @post.likes.count %></span>
          <span class="glyphicon glyphicon glyphicon-bookmark"></span>
          <h2>
      </div>
    </div>
  </div>

  <div class="row">
    <%= image_tag "post1.jpg", class:"img-responsive" %>
    <br>
    <div class="container">

      <br>

      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          <p><%= @post.body %></p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <p>Lorem ipsum dolor sit amet, labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
          <br>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <span><%= @post.category.name %></span>
          <span class="pull-right"><%= @post.created_at%></span>
        </div>
      </div>
      <br>
      <% if can? :edit, @post%>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="DeleteEditPost">
          <span class="pull-right">

            <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-success" %>
            <%= link_to 'Delete', post_path(@post), class: "btn btn-danger", method: :delete, data:{confirm: 'Are you sure?'} %>
          </span>
        </div>
      </div>
      <% else %>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="DeleteEditPost">

          <% if @liked_by_currentuser === false %>
            <%= form_for [@post, @like] do |f| %>
              <div class="form-group ">
                <div class="col-md-3 col-xs-6" style="padding-left:0px;">
                  <%= f.submit "like", class: "btn btn-info btn-block" %>
                  <% @liked_by_currentuser = true %>
                </div>
              </div>
            <% end %>
          <% else %>
            <span class="btn btn-info btn-block">Liked</span>
          </div>
          <% end %>

        </div>
      </div>
      <% end %>
    </div>
    <br>
    <br>


    <div class="container" id="author_info">
      <div class="row" >
        <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" id="author_image">
          <%= image_tag "author1.jpg", class:"img-responsive" %>
        </div>
        <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
          <a href="#"><%= @post.user.first_name %> <%= @post.user.last_name%></a>
          <p><%= @post.user.description %>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
        </div>
      </div>
    </div>
    <br>
    <div class="container" id="changes">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2" id="form">
          <%= form_for [@post, @comment] do |f| %>
            <div class="form-group">
              <label for="comment" class="control-label">Leave Comment</label>
              <%= f.text_area :body, class: "form-control", rows: 4, placeholder: "Comment Body" %>
            </div>
            <div class="form-group ">
              <div class="col-md-3 col-xs-6" style="padding-left:0px;">
                <%= f.submit class: "btn btn-info btn-block" %>
              </div>

            </div>
        
          <br>
          <hr>
          <br>
          <% end %>

          <% @post.comments.each do |c| %>
          <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2" >
                <%= image_tag "author#{@number}.jpg", class:"img-responsive" %>
              </div>
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
              <p><%= c.body %></p>
            </div>

          </div>
          <br>
          <div class="row">
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><%= c.user.first_name %> <%= c.user.last_name %></div>
              <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6" id="comment_date"><span class="pull-right"><%= c.created_at %></span></div>
          </div>
          <br>
          <% if (can? :destroy, c) || (can? :edit, @post)%>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><%= link_to 'Delete Comment', post_comment_path(@post, c), class: "btn btn-danger", method: :delete, data:{confirm: "Are your sure?"} %></div>
          </div>
          <% end %>
          <hr>
          <br>
          <% @number += 1 %>
          <% end %>

          <br>
          <br>
          <div class="row" id="more_Comments">
            <a href="#" class="btn btn-info btn-lg" role="button">More Comments</a>
          </div>
          <br>
        </div>

      </div>

    </div>
  </div>
</div>



<!-- <h1>Show One Post</h1>
<p><%# @post.title %></p>
<p><%# @post.body %></p>
<br>
<%# link_to 'Delete', post_path(@post), method: :delete, data:{confirm: 'Are you sure?'} %>
<%# link_to 'Edit', edit_post_path(@post) %>



<%# comments create here %>
<h2>Comments</h2>


<%# form_for [@post, @comment] do |f| %>
  <%# f.text_area :body %>
  <br>
  <%# f.submit %>
<%# end %>


<h1>Show Comments</h1>
<%# @post.comments.each do |c|%>
  <p><%# c.body %></p>
  <%# link_to 'Delete Comment', post_comment_path(@post, c), method: :delete, data:{confirm: "Are your sure?"} %>
  <hr>
<%# end %> -->