config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/new'
  #
  # get 'password_resets/edit'

  root 'welcome#index'
  get('/change_password', {to:'users#edit_password'})
  put('/change_password', {to:'users#update_password'})

  resources :posts do
    resources :comments, only: [:create, :destroy, :index]
    resources :likes, only: [:create]
  end



  resources :users, only:[:index, :new, :create, :update, :edit]
  resources :sessions, only:[:new, :create] do
    delete :destroy, on: :collection
    #get rid of ":id" in the url
  end
  resources :password_resets, only: [:new, :create, :edit, :update]


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.js"></script> -->
    <!-- <script type = "text/javascript" src="../../../bootstrap-3.3.7-dist/js/bootstrap.min.js"></script> -->
    <!-- <link rel="stylesheet" href="../../assignment5/Blog_post_show.css"> -->
    <!-- <link href="../../../font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css"> -->
    <link href="https://fonts.googleapis.com/css?family=IM+Fell+DW+Pica|Lora|Merriweather" rel="stylesheet">
  </head>

  <body>
    <div id="main">


      <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" id="nav">
        `<div class="container">
          <div class="navbar-header">
              <!-- <a class="navbar-brand" href="#"> -->
                <a class="navbar-brand grow" href="/"><img id="logo" alt="Brand" src="<%= asset_path( 'blog_logo.png') %>"></a>
                <%# image_tag 'blog_logo.png', class: 'navbar-image'%>
                <%# why it does not work?????? %>
                <!-- <img alt="Brand" src="../../assets/images/blog_logo.png"> -->

              <!-- </a> -->
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse navbar-responsive-collapse" id="myNavbar">

            <ul class="nav navbar-nav">
              <li class="nav-item">
                <%= link_to "Home", root_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Posts", posts_path %>
              </li>
              <li class="nav-item">
                <%= link_to "New Post", new_post_path %>
              </li>
              <li class="nav-item">
                <a href="#">About</a>
              </li>
              <li class="nav-item">
                <a href="#">Contact</a>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="nav-item">
                 <% userName = current_user.first_name.upcase %>
                <%= link_to "HELLO,#{userName}", edit_user_path(current_user.id)%>
              </li>
              <li class="nav-item">
                <%= link_to "Change Password", change_password_path %>
              </li>
                <li class="nav-item">
                <%= link_to "Sign Out", sessions_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_path %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign In", new_session_path %>
              </li>
            <% end %>
            </ul>
            <form class="navbar-form navbar-right">
              <div class="form-group">
                <span class="glyphicon glyphicon-search"></span>
                <input type="text" class="form-control" placeholder="Search">
              </div>
            </form>
          </div>

        </div>
      </nav>

    <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">

      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      <%= flash[:alert] %>
    </div>
    <% end %>


    <%= yield %>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-camera fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-square fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <br>
                    <p class="copyright text-muted" id="footer_copyright">Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </div>
    </footer>


  </body>
</html>